name: docgo
description: "A new Flutter project."
publish_to: "none" # Private package, tidak akan dipublish ke pub.dev

# Versioning
version: 1.0.0+1

# Environment
environment:
  sdk: ^3.10.0

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  youtube_player_flutter: ^9.1.3
  flutter_inappwebview: ^6.0.0

  # State management & data
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  http: ^1.1.0
  go_router: ^14.2.0

  # Firebase
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0
  flutter_launcher_icons: ^0.14.4
  socket_io_client: ^3.1.3
  intl: ^0.20.2
  android_alarm_manager_plus: ^5.0.0
  workmanager: ^0.9.0+3
  wakelock_plus: ^1.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/image/
    - assets/icon/

  # Fonts
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
          weight: 400
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 700
